### ISSUE TITLE
"Minimal build script" example fails with default outpath

### ISSUE THREAD

**Issue by ameotoko** [staticjinja/staticjinja#160]
The "minimal build script" from the [docs](https://staticjinja.readthedocs.io/en/stable/user/advanced.html#using-custom-build-scripts) fails for me with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 408, in render_template
    rule = self.get_rule(template.name)
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 329, in get_rule
    raise ValueError("no matching rule")
ValueError: no matching rule

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Sites/test/build.py", line 5, in <module>
    site.render(use_reloader=True)
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 475, in render
    self.render_templates(self.templates)
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 424, in render_templates
    self.render_template(template)
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 412, in render_template
    _ensure_dir(filepath)
  File "/usr/local/lib/python3.9/site-packages/staticjinja/staticjinja.py", line 35, in _ensure_dir
    os.makedirs(os.path.dirname(Path(path)), exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

_disclaimer: I know nothing about Python_

I found that, in these lines below, `Path(path)` returns just a filename, and `os.path.dirname(Path(path))` subsequently returns empty string, which then makes `mkdir()` fail. This only happens when `outpath='.'` (which is the default):

https://github.com/staticjinja/staticjinja/blob/e98e388fe2c06ab8b1fbac27a959500737458948/staticjinja/staticjinja.py#L33-L35

The workaround for me was:

```python
from staticjinja import Site
import os

if __name__ == "__main__":
    site = Site.make_site(outpath=os.path.abspath(os.getcwd()))
    site.render()
```

**Comment by NickCrews** [comment]
Hey @ameotoko, thanks for this, that does indeed look like a bug. I have a fix for it in #163. Thanks!
